[build]
  command = "npm --prefix frontend install --include=dev && npm --prefix frontend run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/api/*"
  to = "https://saytou-1.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
